### PR TITLE
Dantef

### PR DESCRIPTION
**Pull request by dfurioso**
Updates

### CODE REVIEW

**Comment by jcephas** [comment]
You're still working with the old set of folders. For example, when I look at your branch on the website, you don't have any of the most current folders (e.g., you don't have the prospectus folder in your branch). You will need to merge the main branch into your own branch first before pushing your new work. 

First, backup all of your work elsewhere. Then merge main into your branch. Make sure after you select your branch to merge, that you commit and push that change. After you do that, then you can add in your new files and commit and push those files.

**Comment by dfurioso** [comment]
Ok, sorry about that. I think I fixed it! There was an error in one of my
HTML files that was preventing me from merging the main branch into my
local branch, but I think it should be fixed now.

**Comment by jcephas** [comment]
Ok, good, you have the prospectus folder now. Merge main into your branch one more time so that you have the new files that I added today.

**Comment by dfurioso** [comment]
It says I'm up to date with the main brach.

**Comment by jcephas** [comment]
Yes, you are up to date with main (yay!) but you've also added some of your files to Patrick’s folder (not good).

Remove Dictionary.png, Map.jpg, Newspaper.png, Palacio.png, and index.html from 01-ResearchAbstract/Patrick and add those files instead to 01-ResearchAbstract/Dante. Then commit and push again.

Almost there!

**Comment by dfurioso** [comment]
Ok, just did that. I have no idea how those files ended up in Patrick's
folder! So strange. Anyway, it should be good now.

**Pull request merged**
