### PR TITLE
Vanessa Gonzalez Abstract Webpage

### PR DESCRIPTION
**Pull request by vanessagonzalez550**
file:///C:/Users/vrg21/OneDrive/Desktop/root/Vanessa%20Gonzalez_Abstract.html

### CODE REVIEW

**Comment by jcephas** [comment]
You will need to do a few things before I can merge your branch:
1. Remove your reading response and abstract from the main folder.
2. Merge the main branch into your branch (instructions for doing this are in the GitHub tutorial and on Slack).
3. Commit and push.
4. Once the main branch is merged into your branch, you will see the folders for each of the assignments. Put your files in the correct folders.
5. Commit and push.

**Comment by vanessagonzalez550** [comment]
Hi Jay,

I have gone through the process of merging the main branch to my branch
(1-2), however every time I try to save my files to the corresponding
folders, I notice that they do not appear in the folders on the web
platform and only appear on the local drive folders. I have attached
screenshots of this issue:

[image: 1.jpg]
[image: 2.jpg]

**Comment by vanessagonzalez550** [comment]
Actually I noticed that the html file appears on my personal branch... [image:
3.jpg]not on the main

**Comment by vanessagonzalez550** [comment]
Hi Jay, 

I have

**Comment by jcephas** [comment]
Hi Vanessa,

Once you see the files in your branch on the web platform, then that is confirmation that you have successfully pushed your files. The files will only show up in the main branch once I merge your branch into the main branch. I've done that so you can now see your files in the main branch.

**Pull request closed without merging**
